services:
  app:
    build: .
    container_name: elearn-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/elearn_teacher
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Namrata@1805
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - uploads_data:/app/uploads/submissions

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Namrata@1805
      MYSQL_DATABASE: elearn_teacher
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:
  uploads_data:
